name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment (dev/staging/prod)'
        required: true
        default: 'dev'
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Deploy step
        run: echo "Deploying to production..."
